### ISSUE TITLE
Create a blog post on piwik.org/blog to announce the Java Tracker SDK

### ISSUE THREAD

**Issue by mattab** [piwik/piwik-java-tracker#1]
This library has a huge potential to be used by Piwik community. To let everyone know that the tracker SDK is available, it will be ideal to publish a blog post on our blog.

Would you mind drafting a short blog post about the library?

Ideally the blog post would:
- introduce the possibilities of the Java SDK
- list the requirements
- getting started: download, quick setup or link to setup Readme
- small snippets of tracking page views, an event...
- Contribute section: we welcome bug reports and pull requests

Here is the example for iOS SDK:
https://piwik.org/blog/2013/10/mobile-analytics-sdk-beta-release-of-piwik-ios-sdk/

Or for C#:
https://piwik.org/blog/2013/02/c-sharp-tracking-and-analytics-api/

What do you think @BCsorba ?

**Comment by BCsorba** [comment]
Blog post has been submitted for review.

**Comment by mattab** [comment]
@BCsorba Blog post looks good! it's been published @ [Introducing the Piwik Java Tracker – analytics for your Java based applications](https://piwik.org/blog/2015/11/introducing-piwik-java-tracker/) :+1:
