### ISSUE TITLE
maven dependency management problems

### ISSUE THREAD

**Issue by JHQtheOne** [piwik/piwik-java-tracker#12]
I had some trouble using this library in my companies project, due to overlapping and conflicting dependencies. Please consider scoping maven dependencies appropriately.
(i.e I guess Mockito is only used for testing etc.) 

For now I solved my issues by shading your artifact and hiding the transitive dependencies.

**Comment by bcsorba** [comment]
Dependencies have been scoped - we'll keep working to eliminate dependencies as possible.

**Comment by bcsorba** [comment]
Released in v1.0.2
