### ISSUE TITLE
new PiwikTracker() hangs

### ISSUE THREAD

**Issue by rivoduck** [piwik/piwik-java-tracker#14]
I cannot get PiwikTracker to work, when I instantiate a PiwikTracker object it hangs on new PiwikTracker(<myurl>)

I pass my piwik API endpoint as a String object  like "http://piwik.myorganization.com/piwik.php" but it does not return and it does not throw any Exception.

I have the following in my classpath
javax.json-1.0.4.jar
javax.ws.rs-api-2.0.1.jar
jersey-common-2.23.1.jar

(downloaded by hand from maven.apache.org)

Any hint at what I am doing wrong?
Thank you very much!
Andrea

**Comment by bcsorba** [comment]
Hi Andrea,

I would try including the hk2 and the javaee-api jars that are specified in the pom.xml files.  These are currently runtime dependencies of the tracker and the lack of them may be causing your hang.

Let me know if this resolves it!

**Comment by rivoduck** [comment]
Hello Bret,

now I removed the previous jars and included the following:
piwik-java-tracker-1.0.2.jar
hk2-api-2.4.0.jar
hk2-locator-2.4.0.jar
hk2-utils-2.4.0.jar
javax.inject-2.4.0.jar
javaee-api-5.jar

It still hangs on the constructor, I am using Java 1.8, recompiling your code did not change the behaviour either.

Thank you for your help!
Andrea

**Comment by rivoduck** [comment]
Added more jars at no avail
piwik-java-tracker-1.0.2.jar
hk2-api-2.4.0.jar
hk2-locator-2.4.0.jar
hk2-utils-2.4.0.jar
javax.inject-2.4.0.jar
javaee-api-5.jar
jersey-guava-2.20.jar
jersey-common-2.20.jar
aopalliance-repackaged-2.4.0.jar

**Comment by rivoduck** [comment]
Can the problem be relater to the fact that I am using java 1.8?

**Comment by rivoduck** [comment]
Hi Brett,

with these jars it looks like it is working!!!!

piwik-java-tracker-1.0.2.jar
hk2-api-2.4.0.jar
hk2-locator-2.4.0.jar
hk2-utils-2.4.0.jar
javax.inject-2.4.0.jar
jersey-guava-2.20.jar
jersey-common-2.20.jar
aopalliance-repackaged-2.4.0.jar
javax.json-1.0.4.jar
javaee-api-7.0.jar

I replaced javaee-5 with javaee-7 which contains UriBuilder that is not present in javaee-5


Thank you,
Andrea

**Comment by rivoduck** [comment]
I am still not sure if they are all needed or if some jar can be removed

**Comment by rivoduck** [comment]
The software works with Java JDK 1.8 with the following jars included:

piwik-java-tracker-1.0.2.jar
hk2-api-2.4.0.jar
hk2-locator-2.4.0.jar
hk2-utils-2.4.0.jar
javax.inject-2.4.0.jar
jersey-guava-2.20.jar
jersey-common-2.20.jar
aopalliance-repackaged-2.4.0.jar
javax.json-1.0.4.jar
javaee-api-7.0.jar

(downloaded from http://mvnrepository.com/ )

Closing the issue.
Thank you!
Andrea
