### ISSUE TITLE
problem with date rendering

### ISSUE THREAD

**Issue by rivoduck** [piwik/piwik-java-tracker#17]
the class PiwikDate renders the date in a 12-hours format without the AM/PM indication, as a result all actions are logged in the morning!

Changing the following line in both constructors for the PiwikDate class fixes the issue

format = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
into 
format = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

Thank you!
Andrea

**Comment by mattab** [comment]
Good find @rivoduck - and kuddos for quick fix @bcsorba :

**Comment by bcsorba** [comment]
Released in v1.1
