### ISSUE TITLE
SITE_ID Constant

### ISSUE THREAD

**Issue by prismsoundzero** [piwik/piwik-java-tracker#19]
In the PiwikRequest class, the SITE_ID constant equals "idsite" instead of "idSite" thus I get this error in the response:
`{
  "result": "error",
  "message": "Merci de spécifier une valeur pour idSite"
}`

**Comment by bcsorba** [comment]
"idsite" is consistent with the [Tracking API](http://developer.piwik.org/api-reference/tracking-api).  Is it possible that you are constructing the PiwikRequest with a null for siteId or are setting the value as null somewhere in your code?

**Comment by mattab** [comment]
`idsite` is correct for the Tracking API while `idSite` is used for the [Reporting API](http://developer.piwik.org/api-reference/reporting-api)

**Comment by prismsoundzero** [comment]
Ok that's why. Because in my case, I'm using it to call the Reporting API and not the Tracking API. I thought it would be consistent between both APIs so I didn't check the Tracking one.
