### ISSUE TITLE
Publish this project on the Maven central repository

### ISSUE THREAD

**Issue by bcsorba** [piwik/piwik-java-tracker#2]
While dependencies are included with this project, it's often unwieldy for users of this tracker to include lots of libraries.  This also increases the potential that a user may miss a dependency.

Publishing this project to the Maven central repository would resolve this issue and provide a cleaner way to download and include this tracker in projects.

**Comment by mattab** [comment]
:+1:

**Comment by udf2457** [comment]
+1

**Comment by bcsorba** [comment]
See [Maven Central](http://search.maven.org/#artifactdetails%7Corg.piwik.java.tracking%7Cpiwik-java-tracker%7C1.0%7C)

**Comment by mattab** [comment]
Nice, users will appreciate the ease of use from Maven :+1:

**Comment by tholu** [comment]
@bcsorba Planning a new release soon. How did you publish it to Maven Central? CC @mattab

**Comment by bcsorba** [comment]
See https://infra.apache.org/maven-releases.html

**Comment by bcsorba** [comment]
See https://infra.apache.org/maven-releases.html

**Comment by tholu** [comment]
The general Maven release process is clear to me, and I have published to a private Nexus before. Your link seems to indicate releasing Maven artifacts to an internal Apache Nexus. However, I want to publish the new release to [Maven Central](https://search.maven.org/). The current version released there is [1.2](https://search.maven.org/artifact/org.piwik.java.tracking/piwik-java-tracker/1.2/jar).

As I have never released to Maven Central before, the main question for me is the process to authorize me to publish a new version for the `piwik-java-tracker` artifact in the `org.piwik.java.tracking` group on Maven Central. How do they know, that I'm actually allowed to release a new version? Do you need to add me to the group somehow? I already have a Jira Account for the Sonatype Jira and can login to https://oss.sonatype.org/ with it. Great if you can give some guidance here.

**Comment by bcsorba** [comment]
What is your JIRA username? (I presume tholu, but want to confirm). I can open a ticket to give you deployment permissions for the project.

**Comment by tholu** [comment]
Sorry, I missed to add that. `tholu` is correct - thank you!

**Comment by bcsorba** [comment]
Thanks: I updated https://issues.sonatype.org/browse/OSSRH-19145

Feel free to track that discussion.
