### ISSUE TITLE
POM requires Java 1.7 but code uses 1.8 features

### ISSUE THREAD

**Issue by MajorTom4711** [piwik/piwik-java-tracker#22]
Hi,

I tried to integrate the library using jitpack.io which fails (https://jitpack.io/com/github/piwik/piwik-java-tracker/709012c/build.log). I assume this is because Java 1.8 features are used (e.g. map.putIfAbsent for Map in CustomVariableList) but the POM sets Java 1.7 as the target version.

Could you look  into this? Thanks

Kind regards...

**Comment by bcsorba** [comment]
There's an open pull request https://github.com/piwik/piwik-java-tracker/pull/20 addressing this.  This will be fixed by that request or myself in a change and will be released in 1.3

**Comment by MajorTom4711** [comment]
Okay, thank you! I didn't notice the request

**Comment by bcsorba** [comment]
Resolved and will be released in 1.3.  Feel free to build from HEAD and reopen if it's still not compatible.
