### ISSUE TITLE
Let users track Custom Dimensions 

### ISSUE THREAD

**Issue by tsteur** [piwik/piwik-java-tracker#7]
In https://github.com/piwik/piwik/issues/9129 we created a new plugin to track Custom Dimensions.

To the JavaScript Tracker we added a new method `setCustomDimension(int dimensionId, string dimensionValue)`. This sets a tracking API parameter `dimension$dimensionId=$dimensionValue`. Eg `dimension1=foo` or `dimension2=bar`. So the tracking API parameter starts with `dimension` followed by the set `dimensionId`. 

I reckon we should be consistent here with the PHP Tracker and clear all set custom dimensions after the next tracking request was sent. 
eg
```
setCustomDimension(1, 'myvalue1')
setCustomDimension(2, 'myvalue2)
trackPageview()
// now dimension 1 and 2 would be cleared and one has to set values again
```

FYI: Custom Dimensions are similar to Custom Variables. Currently a plugin is needed to use them but in Piwik 3.0 it will be installed by default and at some point we will deprecate Custom Variables (not soon though)

**Comment by bcsorba** [comment]
My biggest concern with adding this functionality to the core API is the same one that you expressed [here](https://github.com/piwik/piwik/issues/9129#issuecomment-153552586), namely that it goes against pattern to have functionality in the core API that is currently only available via a plugin.

It may be better currently to add the functionality for users to add custom tracking parameters to their requests, which appears to be the functionality in the js and php clients.  This would allow users with the plugin to manually set the parameters, effectively allowing the functionality.

I think it may be a good idea however to explore the idea of a plugin framework for this tracker - this would allow all plugin creators to be able to extend the core tracker to their own needs.

I vote to add this functionality when dimensions are integrated into Piwik Core.  Thoughts @tsteur, @mattab ?

**Comment by tsteur** [comment]
I had the same concerns when I added it for PHP-Tracker and made it generic there see: https://github.com/piwik/piwik-php-tracker/pull/15/files 

It's basically a method `setCustomTrackingParameter(parameter, value)` that let's you set a dimension like this: `setCustomTrackingParameter('dimension1', 'my value')`

**Comment by bcsorba** [comment]
We'll go with adding the custom tracking parameter then until this feature is integrated with core.  See https://github.com/piwik/piwik-java-tracker/issues/8

**Comment by tsteur** [comment]
:+1:
