### ISSUE TITLE
Add or fix PiwikRequest.setUserCustomVariable() to put data in insertion order

### ISSUE THREAD

**Issue by rparatc** [piwik/piwik-java-tracker#9]
Unordered user custom variables in piwik.piwik_log_visit table due to PiwikJsonObject class has field map implementation HashMap instead of LinkedHashMap.
Would you be kind enough to fix it?

**Comment by bcsorba** [comment]
Thanks for pointing this out - will be opening up an issue to increase the functionality of setting these custom variables.

**Comment by bcsorba** [comment]
Released in 1.0.1
